name: "Docker"

on:
  workflow_dispatch:

  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/ci"
        tag: "${{ matrix.item }}"
        context: "${{ matrix.item }}"
    strategy:
      matrix:
        include:
          - item: "5.6"
          - item: "5.6-fpm"
          - item: "7.0"
          - item: "7.0-fpm"
          - item: "7.1"
          - item: "7.1-fpm"
          - item: "7.2"
          - item: "7.2-fpm"
          - item: "7.3"
          - item: "7.3-fpm"
          - item: "7.4"
          - item: "7.4-fpm"
          - item: "8.0"
          - item: "8.0-fpm"
          - item: "8.1"
          - item: "8.1-fpm"
          - item: "8.2"
          - item: "8.2-fpm"
          - item: "8.3"
          - item: "8.3-fpm"
          - item: "8.4"
          - item: "8.4-fpm"

      fail-fast: false