name: "Docker"

on:
  workflow_dispatch:

  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/ci"
        tag: "${{ matrix.item }}"
        context: "${{ matrix.item }}"
    strategy:
      matrix:
        include:
          # PHP
          - item: php56
          - item: php56-fpm
          - item: php70
          - item: php70-fpm
          - item: php71
          - item: php71-fpm
          - item: php72
          - item: php72-fpm
          - item: php73
          - item: php73-fpm
          - item: php74
          - item: php74-fpm
          - item: php80
          - item: php80-fpm
          - item: php81
          - item: php81-fpm
          - item: php82
          - item: php82-fpm
          - item: php83
          - item: php83-fpm

      fail-fast: false